### ISSUE TITLE
TRIG\GATE switches for each output in right click menu for CLKD

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/ImpromptuModular#17] opened 2020-05-02 06:24 UTC
Hi Marc!) I found a funny thing on how different resets\clock (gate vs trig) behave in Rack! When a clock module has gates on its outputs it becomes tricky to click on reset to get the right starting point of all modules that can receive clock\reset pair, I tested on BPM LFO and some step sequencers as well. While using trigger outputs makes 100 right behavior and I don't know why :-) How I found that? ZZC Clock has right click options to switch each of the 3 outputs to gates or trigger. And with gates choosen I got similar behavior that was with CLKD and with trigger there was all right while hitting reset button any time. So based on that experience I'd like to suggest you to add trigger\switch in right click menu to CLKD. Cheers!

**Comment by MarcBoule** [comment] 2020-05-02 11:55
I'll think about this, but just so you know, the "100% percent right" you mention is technically not 100% since you have to be very unlucky to click reset while a 10ms trigger is high, but it is still possible and could happen. Clicking reset while a 50% duty cycle clock is high is 50% chance, but a 10ms trigger during a 0.5s interval (120 BPM), means 2%, which translates to 98% in your case above instead of 100% :-) Sorry to be all mathematical with this, but I just want you to know that it's not 100% even with triggers. And once this is establised, it can be bad to actually think it is 100% (during all practice runs) and then when we're finally performing the final take, we are unlucky and manage by accident to hit reset while the trigger happens to be high.

So if I understand, only CLKD would need this, since in Clocked we already have the pulse width control that can already do this.

**Comment by MarcBoule** [comment] 2020-05-02 12:59
After checking, triggers are 1ms, so in this extreme case it would be 99.8 percent right :-) I think I can add this feature though, no problem!

**Comment by vcvrackideas** [comment] 2020-05-02 15:36
Thx for understanding Marc!)

**Comment by MarcBoule** [comment] 2020-05-03 00:48
Ready to test, if you can give it try. Cheers!

![image](https://user-images.githubusercontent.com/33604154/80895746-44893280-8cb6-11ea-9c04-8ebf0d3579d9.png)

**Comment by vcvrackideas** [comment] 2020-05-04 09:26
> Ready to test, if you can give it try. Cheers!
> 
> ![image](https://user-images.githubusercontent.com/33604154/80895746-44893280-8cb6-11ea-9c04-8ebf0d3579d9.png)

thanks Marc, works great! EDIT! - sorry Marc, it generates a trigger each time (1 step position) while adjusting divider\multiplier knob. Don't know how it works on big Clocked brother yet though

**Comment by MarcBoule** [comment] 2020-05-07 17:02
I just saw your edit now, after it was just released, so I'll leave this open until I can fix it.

**Comment by MarcBoule** [comment] 2020-06-21 17:30
After looking into this, I think it's not a bug since the triggers that are emitted happen when the sub clock gets back in sync with the master clock before it see the ratio knob has changed again, so it has no choice but to emit the trigger. Big Clocked does this also when we set the PW to minimum.

If I had a phase-based clock like ZZC, I could probably avoid this, but in my current implementation, I think it's unavoidable.

**Comment by MarcBoule** [comment] 2020-06-21 17:31
So I think I'll close the issue, but feel free to follow up if you like. Cheers!

**Closed as completed by MarcBoule** 2020-06-21 17:31 UTC
