### ISSUE TITLE
why does clckd main bpm different than DAWS

### ISSUE THREAD

**Issue by XtremeSounds** [MarcBoule/ImpromptuModular#41] opened 2021-10-31 21:25 UTC
Hi it seem 120 bpm is slower than DAWS bpm. any reason why?

**Comment by MarcBoule** [comment] 2021-11-01 12:31
Yes, this is typically caused by differences in sample rate in Rack vs DAW. And there seems to be a known current bug in Rack whereby in some cases the displayed sample rate does not match it's internal sample rate, and this can be sometimes fixed by initializing the audio module or deleting it and dropping a new one in its place. This particular message by Steve in the forum talks about this bug:

https://community.vcvrack.com/t/studio-edition-new-patch-stops-processing-of-modules-if-run-standalone/14488/2

**Comment by XtremeSounds** [comment] 2021-11-01 12:45
Using an ableton link module to sync clockd and opening my DAW and pressing play fixes this issue

**Comment by MarcBoule** [comment] 2021-11-01 12:47
Excellent, glad it's resolved. Cheers!

**Closed as completed by MarcBoule** 2021-11-01 12:47 UTC
