### ISSUE TITLE
x1 CLK outputs are twice as fast as BPM

### ISSUE THREAD

**Issue by ivxvm** [MarcBoule/ImpromptuModular#43] opened 2019-06-07 09:53 UTC
I just checked the actual BPM of x1 CLK output via https://getsongbpm.com/tools/tap-tempo and it's twice as fast as BPM setting of Clocked (makes 240 ticks per minute when BPM is 120). Is this by design? I would intuitively expect x1 to make exactly 120 ticks.

Version: 0.6.17

PS: 
I also checked VeeSeeVST version inside Ableton and it makes 120 beats.
It says the version is 0.6.16 there.

**Comment by MarcBoule** [comment] 2019-06-07 12:03
Thanks for the report, but I believe this may be the cause:
https://github.com/MarcBoule/ImpromptuModular#known-issues-
Rack uses the audio module to get its timing, so without one, things can be wonky. Please let me know if ever you are still having problems after adding the Core Audio module and assigning it to a valid sound device.

**Comment by ivxvm** [comment] 2019-06-07 13:56
@MarcBoule 
Thank you, indeed adding Audio fixes the issue. I'm not sure how I even noticed it, it seems at least once I got wrong clock audibly. Maybe I was just experimenting with sequencing and routing and was surprised by fast blinks though. Feel free to close if you don't think this should be fixed on Impromtu side, I will reopen or create another issue if I figure out the way to reproduce the problem audibly.

**Comment by MarcBoule** [comment] 2019-06-07 14:39
It actually can't reasonably be fixed on the Impromptu side, since the timing comes from Rack itself, so the best is just to remember to include an audio module and select a valid sound device. The 2x multiple you noticed could actually also be user dependant, so it's not really fixable on my end. Cheers!

**Closed by MarcBoule** 2019-06-07 14:39 UTC
