### ISSUE TITLE
Gateseq: Lock module

### ISSUE THREAD

**Issue by Eurikon** [MarcBoule/ImpromptuModular#34] opened 2021-02-02 20:07 UTC
Hi Marc, I have been meaning to ask this for a while now.
Could you please add a lock for the module (right click context menu?).

I stopped counting the times that accidental clicks while moving around the patch via click grab with mouse, sometimes causes step events to be deleted or added. 

This of course is not a bug, but it just can happen. 
And usually will only happen when being zoomed out, cause that will make the chance bigger for an accidental mouse click to have effect when hovering over the module in a move.

I hope this makes sense :)

**Comment by MarcBoule** [comment] 2021-02-02 20:44
I think I follow, but you mean when you click with the middle mouse button? I'm not sure I can reproduce what you are experiencing, since when I middle-click to move the Rack around, it doesn't change the steps in GS64.

**Comment by Eurikon** [comment] 2021-02-02 22:17
Hi Marc :)

It happens to me quite often when using a trackpad of the notebook, have not have this happen with a mouse yet.

It also can not be reproduced just like that. 
Sloppy movements over the screen ,sticky fingers, accidental clicks.. try to reproduce those hehe 🙃 

A lock on module level would prevent anything changed on the module itself accidentally, after being happy with its content.

**Comment by Eurikon** [comment] 2021-02-02 22:27
If it is too much coding for an issue that can be resolved by switching to song mode, then I understand that as well.

No worries :)

**Comment by MarcBoule** [comment] 2021-02-02 23:15
I don't think I will lock the whole module, but the grid of steps and the gate types I could do I think. I'll take a look :-)

**Comment by Eurikon** [comment] 2021-02-03 00:16
Yeah sorry I didn't mean the whole module, locking the steps is great enough!

Thanks, Marc! :)

**Comment by MarcBoule** [comment] 2021-02-04 15:09
It's been added to the source and will be part of the next update which should be very soon, but if you build plugins, feel free to pull Impromptu! Cheers,
Marc

**Closed as completed** 2021-02-04 16:51 UTC
Labels: enhancement, done
